### PR TITLE
Async Completion samples

### PR DESCRIPTION
**Pull request by AmadeusW**
This sample demonstrates usage of `IAsyncCompletionItemManager`, `IAsyncCompletionItemManagerProvider`, `IAsyncCompletionSource` and `IAsyncCompletionSourceProvider`, specifically, providing a completion with chemical elements in the `text` content type. 

Some of the interesting features:

* Completion items come from MEF-imported list of elements
* After typing a colon, completion offers values dependent on text before the colon, including the **suggestion mode** (aka builder)
* **DefaultCompletionItemManager** is the same implementation as we use in the editor
* Some items have multiple filters
  * Elements are categorized as metals, non metals, uncategorized or _metalloids_, which means they are both metals and non-metals. I used this to demonstrate items with two filters: you’ll see that there is no metalloid filter, but these items (e.g. Boron, Silicon) will react to both Metals and Non Metals filters

image

### CODE REVIEW

**Comment by madskristensen** [comment]
Thanks!!! The build failed due to NuGet package version references that couldn't be resolved. Please downgrade your NuGet references to ones that are publicly available. Also, use the lowest version of the packages that has the APIs you use (so probably 15.6.x).

**Comment by madskristensen** [comment]
@AmadeusW the nuget versions are still wrong

**Comment by AmadeusW** [comment]
What's the C# version on the build machine? Can this be updated?
Neither `<LangVersion>latest</LangVersion>` nor `<LangVersion>7.1</LangVersion>` seems to work - there are many errors related to 7.1 language features

**Comment by AmadeusW** [comment]
Got a green build thanks to @dgriffen's keen eye!

I'm going to add a readme that explains which parts are relevant:
* IAsyncCompletionItemManager is optional, and we're providing the Editor's manager as an example
* A lot of code in the IAsyncCompletionSource is related to parsing the code, and not purely providing completion

**Comment by dgriffen** [comment]
@AmadeusW I wonder if the new API should go in a separate sample since there may be users that want to use the API in 2017 and they won't be able to figure out how if the sample only shows the 2019 API

**Comment by AmadeusW** [comment]
It is its own sample, a lives in the AsyncCompletion folder.

**Comment by AmadeusW** [comment]
@madskristensen a good build, at last! ✔

**Comment by grokys** [comment]
@AmadeusW @madskristensen the readme says:

> Establishing location of completion You extension does not need to fulfill both roles, but both roles need to be fufilled to begin the completion session.
> If you are extending an existing language, expect the language service to provide the exact location. You may simply provide additional completion items to include in the session.

How do I do this? If I simply return `CompletionStartData.ParticipatesInCompletionIfAny` from `InitializeCompletion` then my `GetCompletionContextAsync` method isn't called.

For context: I'm wanting to add extra completion to the XAML intellisense.

**Comment by AmadeusW** [comment]
@grokys the XAML language service in VS uses legacy APIs and you won't be able to add extra completion items using async API. You'll need to implement `ICompletionSource.AugmentCompletionSession` where you'll add items to the list.

I took a note that you'd like to add items to XAML intellisense, which will help us prioritize work of moving Visual Studio's XML and XAML language service to modern APIs.

**Comment by grokys** [comment]
Thanks @AmadeusW - I've actually tried that but it's pretty glitchy and I often end up with two stacked completion windows. The XAML editor seems pretty non-extensible in general.

Is the plain XML editor any better? Does that support the async API?

**Comment by AmadeusW** [comment]
No XML editor is actually worse because it's using even more legacy API.  Our hope is to adapt the XML implementation from the Xamarin team (working on AXML files - Android XML)

Can you tell me more about the two stacked completion windows? That sounds like a bug. Are you using the async API, or did you see stacked windows when using only `ICompletionSource.AugmentCompletionSession`?

**Pull request merged**
