### PR TITLE
Add EvaluationTimeoutSample projects and readme file

### PR DESCRIPTION
**Pull request by mpeyrotc**
We are adding tutorials for Custom Managed Debugger Visualizers [here](https://review.docs.microsoft.com/en-us/visualstudio/debugger/visualizer-advanced-scenarios?view=vs-2022#handling-long-serialization-time) and customers wanted to be able to download the projects for which we show code snippets. Hence, we are putting them here so that they have easy access to them.

### CODE REVIEW

**Comment by madskristensen** [comment]
Is there a reason you're not using `<PackageReference>` but uses the old `nuget.config` files?

**Comment by mpeyrotc** [comment]
@madskristensen there is no reason, I assume it must have been default behavior from VS since they are .NET Framework projects.

**Comment by madskristensen** [comment]
It would be nice to have these sample follow as many modern and best practices as possible. That includes using PackageReference. I recommend you change it, but it's not a strict rule and we can publish without it. Let me know what you want to do

**Comment by WardenGnaw** [comment]
The WPF project cannot be SDK styled unless we upgrade the version of VS used to build the projects to be at least VS 2019.

https://github.com/microsoft/VSSDK-Extensibility-Samples/blob/2a2f9282360028d9ab761c6c37ee2ac4320ebd57/appveyor.yml#L2

 Related: https://github.com/dotnet/installer/issues/213

**Comment by mpeyrotc** [comment]
@madskristensen I think it is ready for check-in :)

**Comment by madskristensen** [comment]
Thanks

**Pull request merged**
