### PR TITLE
Fix build break in appveyor

### PR DESCRIPTION
**Pull request by AArnott**

### CODE REVIEW

**Comment by AArnott** [comment]
This resolves the first reason for a break. But even still, there's a CreatePkgDef.exe failure without a logged message.

@AlexEyler do you have cycles to investigate that failure? Feel free to add commits to this PR if you can fix it.

**Comment by AlexEyler** [comment]
@AArnott I can look into it - I haven't seen a build failure with that though. Maybe this PR build will fail and then I can take a look.

**Comment by AlexEyler** [comment]
Oh yeah I see it now - let me see.

**Comment by AlexEyler** [comment]
(maybe updating the build tools reference will help - I can't repro locally).

**Comment by AArnott** [comment]
> maybe updating the build tools reference will help - I can't repro locally

Good idea. I couldn't repro locally either.

**Comment by AlexEyler** [comment]
Yeah, that seemed to do the trick. Are there any other changes you want to do? Otherwise feel free to merge.

**Comment by AArnott** [comment]
I don't have merge privileges. Please go for it!

**Pull request merged**
