### PR TITLE
Update to VS2017/2015

### PR DESCRIPTION
**Pull request by yannduran**
These commits update the OptionsPage project to open/run in both VS 2015/2017.

### CODE REVIEW

**Comment by yannduran** [comment]
@justcla This PR replaces the one I accidentally made in Tim's fork.

**Comment by justcla** [comment]
Why so many changes? Hard to tell which parts relate to the upgrade.

**Comment by yannduran** [comment]
It would have all been spelled out in the first pull request as I did smaller commits, but when I redid it I just added it all it one commit. I do remember though when I was looking at the diff, that they were a bunch of things in there that weren’t actually my changes.

What I did was save the working folder from the first fork, deleted Tim’s fork, forked from the MS repo, then cloned it, then copied over my changes, committed, then created the PR. It wasn’t until after that I just happened to look at the diff out of curiosity that I saw all these changes that I don’t remember making.

The few small things I changed were because when I ran the project myself, there were a couple of confusing bits, so I simplified in a couple of places.

Would you prefer that I do it again?

**Comment by yannduran** [comment]
@justcla Part of the problem is that all of the samples are in **one** big repo. This enables all sorts of undesirable situations, and is muche harder to maintain.

I saved the changes that I made to the project, but I guess when I pulled down the MS repo, instead of Tim's fork, other changes may have come with it. Maybe Tim had already done some cleaning up of this sample?

What do you think of the idea of making each sample its own repo?

**Pull request closed without merging**
