### PR TITLE
Enable appveyor builds

### PR DESCRIPTION
**Pull request by AArnott**
This enables this project to be automatically built in the cloud on AppVeyor.

This can then be used (optionally) as pull request build validation.

### CODE REVIEW

**Comment by AlexEyler** [comment]
Thanks!!

**Comment by AArnott** [comment]
Connected appveyor build: https://ci.appveyor.com/project/AlexEyler/vssdk-extensibility-samples

**Comment by AlexEyler** [comment]
Yeah, once we fix all the build issues then I can put in the badge, I just don't like having the failed badge show up all the time :)

**Comment by AArnott** [comment]
agreed

**Pull request merged**
